- name: test
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        urls:
          - http://10.10.10.149
        delay: 5
  rules:
    - name: Restart httpd
      condition: event.url_check.status == "down"
      throttle:
        once_within: 30 seconds
        group_by_attributes:
          - event.url_check.url
      action:
        run_job_template:
          name: restart_httpd
          organization: Default
