- name: test
  hosts: localhost
  sources:
    - ansible.eda.kafka:
       host: 10.10.10.149
       port: 9092
       topic: FirstKafkaTopic
  rules:
    - name: Incident
      condition: event.messages == "Bad"
      action:
       run_job_template:
         name: EDA_Demo
         organization: Default
